export const MIXER_COLOR_SETS = [
  {
    key: "7",
    name: "Audiotool",
    nexusIndex: 0,
    background: "#50c998ff",
    print: "#183629ff",
  },
  {
    key: "8",
    name: "Cerulean",
    nexusIndex: 1,
    background: "#77ebefff",
    print: "#1a3536ff",
  },
  {
    key: "9",
    name: "Indigo",
    nexusIndex: 2,
    background: "#5490eeff",
    print: "#1f3050ff",
  },
  {
    key: "10",
    name: "Blueberry Muffin",
    nexusIndex: 3,
    background: "#a495fbff",
    print: "#29276bff",
  },
  {
    key: "11",
    name: "Electra",
    nexusIndex: 4,
    background: "#a456f7ff",
    print: "#402061ff",
  },
  {
    key: "12",
    name: "Pink",
    nexusIndex: 5,
    background: "#eb94faff",
    print: "#491f51ff",
  },
  {
    key: "1",
    name: "Strawberry",
    nexusIndex: 6,
    background: "#fa5b46ff",
    print: "#5a1b13ff",
  },
  {
    key: "2",
    name: "Bonbon",
    nexusIndex: 7,
    background: "#ffb877ff",
    print: "#422b18ff",
  },
  {
    key: "3",
    name: "Sun",
    nexusIndex: 8,
    background: "#b78761ff",
    print: "#1a140eff",
  },
  {
    key: "4",
    name: "Lemon",
    nexusIndex: 9,
    background: "#ffebb1ff",
    print: "#5a4d26ff",
  },
  {
    key: "5",
    name: "Sprout",
    nexusIndex: 10,
    background: "#f9f075ff",
    print: "#343113ff",
  },
  {
    key: "6",
    name: "Rain",
    nexusIndex: 11,
    background: "#b2e984ff",
    print: "#243515ff",
  },
  {
    key: "2s",
    name: "Sahara",
    nexusIndex: 12,
    background: "#e3c0a2ff",
    print: "#3a2e23ff",
  },
  {
    key: "3s",
    name: "Beach",
    nexusIndex: 13,
    background: "#a48c7aff",
    print: "#382f28ff",
  },
  {
    key: "4s",
    name: "Leaf",
    nexusIndex: 14,
    background: "#f3ebd7ff",
    print: "#343024ff",
  },
  {
    key: "5s",
    name: "Retro",
    nexusIndex: 15,
    background: "#8d9658ff",
    print: "#2f321aff",
  },
  {
    key: "6s",
    name: "Eucalyptus",
    nexusIndex: 16,
    background: "#9ebe85ff",
    print: "#2a3323ff",
  },
  {
    key: "7s",
    name: "Blue Vanilla",
    nexusIndex: 17,
    background: "#6c9a89ff",
    print: "#21342dff",
  },
  {
    key: "8s",
    name: "Still",
    nexusIndex: 18,
    background: "#9cd0d1ff",
    print: "#1f3434ff",
  },
  {
    key: "9s",
    name: "Dream",
    nexusIndex: 19,
    background: "#92a4bfff",
  },
  {
    key: "10s",
    name: "Mouse Gray",
    nexusIndex: 20,
    background: "#b4aee4ff",
    print: "#302f3eff",
  },
  {
    key: "11s",
    name: "Mauve",
    nexusIndex: 21,
    background: "#a285beff",
    print: "#392a47ff",
  },
  {
    key: "12s",
    name: "Blush",
    nexusIndex: 22,
    background: "#ecd0f0ff",
    print: "#3a2c3cff",
  },
  {
    key: "1s",
    name: "Wood",
    nexusIndex: 23,
    background: "#dd8d8aff",
    print: "#472827ff",
  },
  {
    key: "7d",
    name: "Reef",
    nexusIndex: 24,
    background: "#1f5841ff",
    print: "#50c998ff",
  },
  {
    key: "8d",
    name: "Ocean",
    nexusIndex: 25,
    background: "#2b8c90ff",
    print: "#2cc7cdff",
  },
  {
    key: "9d",
    name: "Polar Night",
    nexusIndex: 26,
    background: "#243f6bff",
    print: "#5490eeff",
  },
  {
    key: "10d",
    name: "Plum",
    nexusIndex: 27,
    background: "#5559f6ff",
    print: "#cbbefeff",
  },
  {
    key: "11d",
    name: "Purple Haze",
    nexusIndex: 28,
    background: "#682fa6ff",
    print: "#d1a0fcff",
  },
  {
    key: "12d",
    name: "Lipstick",
    nexusIndex: 29,
    background: "#c93be8ff",
    print: "#eb94faff",
  },
  {
    key: "1d",
    name: "Crimson",
    nexusIndex: 30,
    background: "#962119ff",
    print: "#ff9984ff",
  },
  {
    key: "2d",
    name: "Zeitgeist",
    nexusIndex: 31,
    background: "#b37032ff",
    print: "#ff9d42ff",
  },
  {
    key: "3d",
    name: "Moussaka",
    nexusIndex: 32,
    background: "#523a27ff",
    print: "#d1ad93ff",
  },
  {
    key: "4d",
    name: "Circuit",
    nexusIndex: 33,
    background: "#927e38ff",
    print: "#e4c451ff",
  },
  {
    key: "5d",
    name: "Vacuum",
    nexusIndex: 34,
    background: "#535017ff",
    print: "#beb915ff",
  },
  {
    key: "6d",
    name: "Racing Green",
    nexusIndex: 35,
    background: "#528e25ff",
    print: "#83dd3fff",
  },
  {
    key: "13",
    name: "Chocolate",
    nexusIndex: 36,
    background: "#ed3366ff",
    print: "#591927ff",
  },
  {
    key: "13s",
    name: "Rosy Brown",
    nexusIndex: 37,
    background: "#b8677fff",
    print: "#4b2530ff",
  },
  {
    key: "13d",
    name: "Bistre",
    nexusIndex: 38,
    background: "#961d3eff",
    print: "#fe96a4ff",
  },
  {
    key: "14",
    name: "Ghost",
    nexusIndex: 39,
    background: "#d9d8e2ff",
    print: "#303037ff",
  },
  {
    key: "14s",
    name: "Bright Gray",
    nexusIndex: 40,
    background: "#8e8ea8ff",
    print: "#303037ff",
  },
  {
    key: "14d",
    name: "Dark Gray",
    nexusIndex: 41,
    background: "#303037ff",
    print: "#8e8ea8ff",
  },
];
