export const MIXER_COLORS = [
  {
    key: "7",
    name: "Audiotool",
    nexusIndex: 0,
    variables: {
      base: "#20b884ff",
      regionBody: "#20b884ff",
      regionBodyAlt: "#20b884ff",
      regionHeader: "#50c998ff",
      regionHeaderActive: "#50c998ff",
      regionContent: "#183629ff",
      loopRangeHover: "#83d7b1ff",
      loopRangeDefault: "#50c998ff",
      loopRangeActive: "#20b884ff",
      loopEdgeHover: "#216a4eff",
      loopEdgeDefault: "#1f5841ff",
      loopEdgeActive: "#1c4735ff",
      midiFillHover: "#83d7b1ff",
      midiBorderHover: "#83d7b1ff",
      midiFillDefault: "#50c998ff",
      midiBorderDefault: "#83d7b1ff",
      midiFillActive: "#20b884ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#50c998ff",
    },
  },
  {
    key: "8",
    name: "Cerulean",
    nexusIndex: 1,
    variables: {
      base: "#2bdbe2ff",
      regionBody: "#2bdbe2ff",
      regionBodyAlt: "#2bdbe2ff",
      regionHeader: "#77ebefff",
      regionHeaderActive: "#77ebefff",
      regionContent: "#1a3536ff",
      loopRangeHover: "#77ebefff",
      loopRangeDefault: "#2bdbe2ff",
      loopRangeActive: "#2cc7cdff",
      loopEdgeHover: "#26676aff",
      loopEdgeDefault: "#235658ff",
      loopEdgeActive: "#1f4547ff",
      midiFillHover: "#77ebefff",
      midiBorderHover: "#77ebefff",
      midiFillDefault: "#2bdbe2ff",
      midiBorderDefault: "#77ebefff",
      midiFillActive: "#2cc7cdff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#77ebefff",
    },
  },
  {
    key: "9",
    name: "Indigo",
    nexusIndex: 2,
    variables: {
      base: "#2b7fe3ff",
      regionBody: "#2b7fe3ff",
      regionBodyAlt: "#2b7fe3ff",
      regionHeader: "#5490eeff",
      regionHeaderActive: "#5490eeff",
      regionContent: "#1f3050ff",
      loopRangeHover: "#5490eeff",
      loopRangeDefault: "#2b7fe3ff",
      loopRangeActive: "#2b6fc3ff",
      loopEdgeHover: "#2a5ea5ff",
      loopEdgeDefault: "#274e87ff",
      loopEdgeActive: "#243f6bff",
      midiFillHover: "#5490eeff",
      midiBorderHover: "#5490eeff",
      midiFillDefault: "#2b7fe3ff",
      midiBorderDefault: "#5490eeff",
      midiFillActive: "#2b6fc3ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#5490eeff",
    },
  },
  {
    key: "10",
    name: "Blueberry Muffin",
    nexusIndex: 3,
    variables: {
      base: "#8d80faff",
      regionBody: "#8d80faff",
      regionBodyAlt: "#8d80faff",
      regionHeader: "#a495fbff",
      regionHeaderActive: "#a495fbff",
      regionContent: "#29276bff",
      loopRangeHover: "#a495fbff",
      loopRangeDefault: "#8d80faff",
      loopRangeActive: "#746df8ff",
      loopEdgeHover: "#3b4ae2ff",
      loopEdgeDefault: "#373eb8ff",
      loopEdgeActive: "#313291ff",
      midiFillHover: "#a495fbff",
      midiBorderHover: "#a495fbff",
      midiFillDefault: "#8d80faff",
      midiBorderDefault: "#a495fbff",
      midiFillActive: "#746df8ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#a495fbff",
    },
  },
  {
    key: "11",
    name: "Electra",
    nexusIndex: 4,
    variables: {
      base: "#923cf2ff",
      regionBody: "#923cf2ff",
      regionBodyAlt: "#923cf2ff",
      regionHeader: "#a456f7ff",
      regionHeaderActive: "#a456f7ff",
      regionContent: "#402061ff",
      loopRangeHover: "#a456f7ff",
      loopRangeDefault: "#a456f7ff",
      loopRangeActive: "#923cf2ff",
      loopEdgeHover: "#7d36cbff",
      loopEdgeDefault: "#682fa6ff",
      loopEdgeActive: "#542883ff",
      midiFillHover: "#a456f7ff",
      midiBorderHover: "#b470f9ff",
      midiFillDefault: "#a456f7ff",
      midiBorderDefault: "#b470f9ff",
      midiFillActive: "#923cf2ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#a456f7ff",
    },
  },
  {
    key: "12",
    name: "Pink",
    nexusIndex: 5,
    variables: {
      base: "#e377f8ff",
      regionBody: "#e377f8ff",
      regionBodyAlt: "#e377f8ff",
      regionHeader: "#eb94faff",
      regionHeaderActive: "#eb94faff",
      regionContent: "#491f51ff",
      loopRangeHover: "#eb94faff",
      loopRangeDefault: "#e377f8ff",
      loopRangeActive: "#da55f6ff",
      loopEdgeHover: "#9331a8ff",
      loopEdgeDefault: "#792b8aff",
      loopEdgeActive: "#61256dff",
      midiFillHover: "#eb94faff",
      midiBorderHover: "#eb94faff",
      midiFillDefault: "#e377f8ff",
      midiBorderDefault: "#eb94faff",
      midiFillActive: "#da55f6ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#eb94faff",
    },
  },
  {
    key: "1",
    name: "Strawberry",
    nexusIndex: 6,
    variables: {
      base: "#f1342aff",
      regionBody: "#f1342aff",
      regionBodyAlt: "#f1342aff",
      regionHeader: "#fa5b46ff",
      regionHeaderActive: "#fa5b46ff",
      regionContent: "#5a1b13ff",
      loopRangeHover: "#fa5b46ff",
      loopRangeDefault: "#f1342aff",
      loopRangeActive: "#d8221eff",
      loopEdgeHover: "#962119ff",
      loopEdgeDefault: "#781e16ff",
      loopEdgeActive: "#5a1b13ff",
      midiFillHover: "#fa5b46ff",
      midiBorderHover: "#fa5b46ff",
      midiFillDefault: "#f1342aff",
      midiBorderDefault: "#fa5b46ff",
      midiFillActive: "#d8221eff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#fa5b46ff",
    },
  },
  {
    key: "2",
    name: "Bonbon",
    nexusIndex: 7,
    variables: {
      base: "#ff9d42ff",
      regionBody: "#ff9d42ff",
      regionBodyAlt: "#ff9d42ff",
      regionHeader: "#ffb877ff",
      regionHeaderActive: "#ffb877ff",
      regionContent: "#422b18ff",
      loopRangeHover: "#ffb877ff",
      loopRangeDefault: "#ff9d42ff",
      loopRangeActive: "#e58e3dff",
      loopEdgeHover: "#845328ff",
      loopEdgeDefault: "#6d4523ff",
      loopEdgeActive: "#57381eff",
      midiFillHover: "#ffb877ff",
      midiBorderHover: "#ffb877ff",
      midiFillDefault: "#ff9d42ff",
      midiBorderDefault: "#ffb877ff",
      midiFillActive: "#e58e3dff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#ffb877ff",
    },
  },
  {
    key: "3",
    name: "Sun",
    nexusIndex: 8,
    variables: {
      base: "#a97449ff",
      regionBody: "#a97449ff",
      regionBodyAlt: "#a97449ff",
      regionHeader: "#b78761ff",
      regionHeaderActive: "#b78761ff",
      regionContent: "#1a140eff",
      loopRangeHover: "#b78761ff",
      loopRangeDefault: "#a97449ff",
      loopRangeActive: "#926540ff",
      loopEdgeHover: "#67482fff",
      loopEdgeDefault: "#523a27ff",
      loopEdgeActive: "#3e2d1fff",
      midiFillHover: "#b78761ff",
      midiBorderHover: "#b78761ff",
      midiFillDefault: "#a97449ff",
      midiBorderDefault: "#b78761ff",
      midiFillActive: "#926540ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#b78761ff",
    },
  },
  {
    key: "4",
    name: "Lemon",
    nexusIndex: 9,
    variables: {
      base: "#f9d75fff",
      regionBody: "#f9d75fff",
      regionBodyAlt: "#f9d75fff",
      regionHeader: "#ffebb1ff",
      regionHeaderActive: "#ffebb1ff",
      regionContent: "#5a4d26ff",
      loopRangeHover: "#ffebb1ff",
      loopRangeDefault: "#f9d75fff",
      loopRangeActive: "#e4c451ff",
      loopEdgeHover: "#7f6d32ff",
      loopEdgeDefault: "#6c5d2cff",
      loopEdgeActive: "#5a4d26ff",
      midiFillHover: "#ffebb1ff",
      midiBorderHover: "#ffebb1ff",
      midiFillDefault: "#f9d75fff",
      midiBorderDefault: "#ffebb1ff",
      midiFillActive: "#e4c451ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#ffebb1ff",
    },
  },
  {
    key: "5",
    name: "Sprout",
    nexusIndex: 10,
    variables: {
      base: "#e4df08ff",
      regionBody: "#e4df08ff",
      regionBodyAlt: "#e4df08ff",
      regionHeader: "#f9f075ff",
      regionHeaderActive: "#f9f075ff",
      regionContent: "#343113ff",
      loopRangeHover: "#aba718ff",
      loopRangeDefault: "#999419ff",
      loopRangeActive: "#87831aff",
      loopEdgeHover: "#646118ff",
      loopEdgeDefault: "#535017ff",
      loopEdgeActive: "#434115ff",
      midiFillHover: "#aba718ff",
      midiBorderHover: "#aba718ff",
      midiFillDefault: "#999419ff",
      midiBorderDefault: "#aba718ff",
      midiFillActive: "#87831aff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#f9f075ff",
    },
  },
  {
    key: "6",
    name: "Rain",
    nexusIndex: 11,
    variables: {
      base: "#83dd3fff",
      regionBody: "#83dd3fff",
      regionBodyAlt: "#83dd3fff",
      regionHeader: "#b2e984ff",
      regionHeaderActive: "#b2e984ff",
      regionContent: "#243515ff",
      loopRangeHover: "#b2e984ff",
      loopRangeDefault: "#83dd3fff",
      loopRangeActive: "#70ca2bff",
      loopEdgeHover: "#3f691fff",
      loopEdgeDefault: "#36571cff",
      loopEdgeActive: "#2d4619ff",
      midiFillHover: "#b2e984ff",
      midiBorderHover: "#b2e984ff",
      midiFillDefault: "#83dd3fff",
      midiBorderDefault: "#b2e984ff",
      midiFillActive: "#70ca2bff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#b2e984ff",
    },
  },
  {
    key: "2s",
    name: "Sahara",
    nexusIndex: 12,
    variables: {
      base: "#d8ac84ff",
      regionBody: "#d8ac84ff",
      regionBodyAlt: "#d8ac84ff",
      regionHeader: "#e3c0a2ff",
      regionHeaderActive: "#e3c0a2ff",
      regionContent: "#3a2e23ff",
      loopRangeHover: "#e3c0a2ff",
      loopRangeDefault: "#d8ac84ff",
      loopRangeActive: "#c8996dff",
      loopEdgeHover: "#735941ff",
      loopEdgeDefault: "#5f4a37ff",
      loopEdgeActive: "#4d3c2dff",
      midiFillHover: "#e3c0a2ff",
      midiBorderHover: "#e3c0a2ff",
      midiFillDefault: "#d8ac84ff",
      midiBorderDefault: "#e3c0a2ff",
      midiFillActive: "#c8996dff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#e3c0a2ff",
    },
  },
  {
    key: "3s",
    name: "Beach",
    nexusIndex: 13,
    variables: {
      base: "#957a66ff",
      regionBody: "#957a66ff",
      regionBodyAlt: "#957a66ff",
      regionHeader: "#a48c7aff",
      regionHeaderActive: "#a48c7aff",
      regionContent: "#382f28ff",
      loopRangeHover: "#a48c7aff",
      loopRangeDefault: "#957a66ff",
      loopRangeActive: "#826a57ff",
      loopEdgeHover: "#5c4b3fff",
      loopEdgeDefault: "#493d33ff",
      loopEdgeActive: "#382f28ff",
      midiFillHover: "#a48c7aff",
      midiBorderHover: "#a48c7aff",
      midiFillDefault: "#957a66ff",
      midiBorderDefault: "#a48c7aff",
      midiFillActive: "#826a57ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#a48c7aff",
    },
  },
  {
    key: "4s",
    name: "Leaf",
    nexusIndex: 14,
    variables: {
      base: "#e7d8b0ff",
      regionBody: "#e7d8b0ff",
      regionBodyAlt: "#e7d8b0ff",
      regionHeader: "#f3ebd7ff",
      regionHeaderActive: "#f3ebd7ff",
      regionContent: "#343024ff",
      loopRangeHover: "#f3ebd7ff",
      loopRangeDefault: "#e7d8b0ff",
      loopRangeActive: "#d8c689ff",
      loopEdgeHover: "#675e42ff",
      loopEdgeDefault: "#554e37ff",
      loopEdgeActive: "#453f2dff",
      midiFillHover: "#f3ebd7ff",
      midiBorderHover: "#f3ebd7ff",
      midiFillDefault: "#e7d8b0ff",
      midiBorderDefault: "#f3ebd7ff",
      midiFillActive: "#d8c689ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#f3ebd7ff",
    },
  },
  {
    key: "5s",
    name: "Retro",
    nexusIndex: 15,
    variables: {
      base: "#7a853eff",
      regionBody: "#7a853eff",
      regionBodyAlt: "#7a853eff",
      regionHeader: "#8d9658ff",
      regionHeaderActive: "#8d9658ff",
      regionContent: "#2f321aff",
      loopRangeHover: "#8d9658ff",
      loopRangeDefault: "#7a853eff",
      loopRangeActive: "#6a7433ff",
      loopEdgeHover: "#4b5226ff",
      loopEdgeDefault: "#3d4220ff",
      loopEdgeActive: "#2f321aff",
      midiFillHover: "#8d9658ff",
      midiBorderHover: "#8d9658ff",
      midiFillDefault: "#7a853eff",
      midiBorderDefault: "#8d9658ff",
      midiFillActive: "#6a7433ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#8d9658ff",
    },
  },
  {
    key: "6s",
    name: "Eucalyptus",
    nexusIndex: 16,
    variables: {
      base: "#87ad6aff",
      regionBody: "#87ad6aff",
      regionBodyAlt: "#87ad6aff",
      regionHeader: "#9ebe85ff",
      regionHeaderActive: "#9ebe85ff",
      regionContent: "#2a3323ff",
      loopRangeHover: "#9ebe85ff",
      loopRangeDefault: "#87ad6aff",
      loopRangeActive: "#799a60ff",
      loopEdgeHover: "#506440ff",
      loopEdgeDefault: "#435336ff",
      loopEdgeActive: "#36432cff",
      midiFillHover: "#9ebe85ff",
      midiBorderHover: "#9ebe85ff",
      midiFillDefault: "#87ad6aff",
      midiBorderDefault: "#9ebe85ff",
      midiFillActive: "#799a60ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#9ebe85ff",
    },
  },
  {
    key: "7s",
    name: "Blue Vanilla",
    nexusIndex: 17,
    variables: {
      base: "#548a77ff",
      regionBody: "#548a77ff",
      regionBodyAlt: "#548a77ff",
      regionHeader: "#6c9a89ff",
      regionHeaderActive: "#6c9a89ff",
      regionContent: "#21342dff",
      loopRangeHover: "#84aa9cff",
      loopRangeDefault: "#6c9a89ff",
      loopRangeActive: "#548a77ff",
      loopEdgeHover: "#396757ff",
      loopEdgeDefault: "#315549ff",
      loopEdgeActive: "#29453bff",
      midiFillHover: "#84aa9cff",
      midiBorderHover: "#84aa9cff",
      midiFillDefault: "#6c9a89ff",
      midiBorderDefault: "#84aa9cff",
      midiFillActive: "#548a77ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#6c9a89ff",
    },
  },
  {
    key: "8s",
    name: "Still",
    nexusIndex: 18,
    variables: {
      base: "#78c0c2ff",
      regionBody: "#78c0c2ff",
      regionBodyAlt: "#78c0c2ff",
      regionHeader: "#9cd0d1ff",
      regionHeaderActive: "#9cd0d1ff",
      regionContent: "#1f3434ff",
      loopRangeHover: "#9cd0d1ff",
      loopRangeDefault: "#78c0c2ff",
      loopRangeActive: "#52b0b3ff",
      loopEdgeHover: "#356668ff",
      loopEdgeDefault: "#2e5556ff",
      loopEdgeActive: "#274445ff",
      midiFillHover: "#9cd0d1ff",
      midiBorderHover: "#9cd0d1ff",
      midiFillDefault: "#78c0c2ff",
      midiBorderDefault: "#9cd0d1ff",
      midiFillActive: "#52b0b3ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#9cd0d1ff",
    },
  },
  {
    key: "9s",
    name: "Dream",
    nexusIndex: 19,
    variables: {
      base: "#7c92b2ff",
      regionBody: "#7c92b2ff",
      regionBodyAlt: "#7c92b2ff",
      regionHeader: "#92a4bfff",
      regionHeaderActive: "#92a4bfff",
      regionContent: "#273140ff",
      loopRangeHover: "#92a4bfff",
      loopRangeDefault: "#7c92b2ff",
      loopRangeActive: "#6681a6ff",
      loopEdgeHover: "#466081ff",
      loopEdgeDefault: "#3c506aff",
      loopEdgeActive: "#314055ff",
      midiFillHover: "#92a4bfff",
      midiBorderHover: "#92a4bfff",
      midiFillDefault: "#7c92b2ff",
      midiBorderDefault: "#92a4bfff",
      midiFillActive: "#6681a6ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#92a4bfff",
    },
  },
  {
    key: "10s",
    name: "Mouse Gray",
    nexusIndex: 20,
    variables: {
      base: "#a19bddff",
      regionBody: "#a19bddff",
      regionBodyAlt: "#a19bddff",
      regionHeader: "#b4aee4ff",
      regionHeaderActive: "#b4aee4ff",
      regionContent: "#302f3eff",
      loopRangeHover: "#b4aee4ff",
      loopRangeDefault: "#a19bddff",
      loopRangeActive: "#908ac4ff",
      loopEdgeHover: "#5e5a7eff",
      loopEdgeDefault: "#4e4b68ff",
      loopEdgeActive: "#3f3d53ff",
      midiFillHover: "#b4aee4ff",
      midiBorderHover: "#b4aee4ff",
      midiFillDefault: "#a19bddff",
      midiBorderDefault: "#b4aee4ff",
      midiFillActive: "#908ac4ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#b4aee4ff",
    },
  },
  {
    key: "11s",
    name: "Mauve",
    nexusIndex: 21,
    variables: {
      base: "#9272b3ff",
      regionBody: "#9272b3ff",
      regionBodyAlt: "#9272b3ff",
      regionHeader: "#a285beff",
      regionHeaderActive: "#a285beff",
      regionContent: "#392a47ff",
      loopRangeHover: "#a285beff",
      loopRangeDefault: "#9272b3ff",
      loopRangeActive: "#825fa8ff",
      loopEdgeHover: "#5c4377ff",
      loopEdgeDefault: "#4a375fff",
      loopEdgeActive: "#392a47ff",
      midiFillHover: "#a285beff",
      midiBorderHover: "#a285beff",
      midiFillDefault: "#9272b3ff",
      midiBorderDefault: "#a285beff",
      midiFillActive: "#825fa8ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#a285beff",
    },
  },
  {
    key: "12s",
    name: "Blush",
    nexusIndex: 22,
    variables: {
      base: "#e1b9e8ff",
      regionBody: "#e1b9e8ff",
      regionBodyAlt: "#e1b9e8ff",
      regionHeader: "#ecd0f0ff",
      regionHeaderActive: "#ecd0f0ff",
      regionContent: "#3a2c3cff",
      loopRangeHover: "#ecd0f0ff",
      loopRangeDefault: "#e1b9e8ff",
      loopRangeActive: "#d7a2e0ff",
      loopEdgeHover: "#735478ff",
      loopEdgeDefault: "#5f4663ff",
      loopEdgeActive: "#4c394fff",
      midiFillHover: "#ecd0f0ff",
      midiBorderHover: "#e1b9e8ff",
      midiFillDefault: "#e1b9e8ff",
      midiBorderDefault: "#e1b9e8ff",
      midiFillActive: "#d7a2e0ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#ecd0f0ff",
    },
  },
  {
    key: "1s",
    name: "Wood",
    nexusIndex: 23,
    variables: {
      base: "#d37675ff",
      regionBody: "#d37675ff",
      regionBodyAlt: "#d37675ff",
      regionHeader: "#dd8d8aff",
      regionHeaderActive: "#dd8d8aff",
      regionContent: "#472827ff",
      loopRangeHover: "#dd8d8aff",
      loopRangeDefault: "#d37675ff",
      loopRangeActive: "#c46262ff",
      loopEdgeHover: "#8f4a49ff",
      loopEdgeDefault: "#763e3dff",
      loopEdgeActive: "#5e3332ff",
      midiFillHover: "#dd8d8aff",
      midiBorderHover: "#dd8d8aff",
      midiFillDefault: "#d37675ff",
      midiBorderDefault: "#dd8d8aff",
      midiFillActive: "#c46262ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#dd8d8aff",
    },
  },
  {
    key: "7d",
    name: "Reef",
    nexusIndex: 24,
    variables: {
      base: "#1c4735ff",
      regionBody: "#1c4735ff",
      regionBodyAlt: "#1c4735ff",
      regionHeader: "#1f5841ff",
      regionHeaderActive: "#1f5841ff",
      regionContent: "#50c998ff",
      loopRangeHover: "#227d5bff",
      loopRangeDefault: "#216a4eff",
      loopRangeActive: "#1f5841ff",
      loopEdgeHover: "#83d7b1ff",
      loopEdgeDefault: "#50c998ff",
      loopEdgeActive: "#20b884ff",
      midiFillHover: "#227d5bff",
      midiBorderHover: "#227d5bff",
      midiFillDefault: "#216a4eff",
      midiBorderDefault: "#227d5bff",
      midiFillActive: "#1f5841ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#1f5841ff",
    },
  },
  {
    key: "8d",
    name: "Ocean",
    nexusIndex: 25,
    variables: {
      base: "#297a7dff",
      regionBody: "#297a7dff",
      regionBodyAlt: "#297a7dff",
      regionHeader: "#2b8c90ff",
      regionHeaderActive: "#2b8c90ff",
      regionContent: "#2cc7cdff",
      loopRangeHover: "#2b8c90ff",
      loopRangeDefault: "#297a7dff",
      loopRangeActive: "#26676aff",
      loopEdgeHover: "#77ebefff",
      loopEdgeDefault: "#2bdbe2ff",
      loopEdgeActive: "#2cc7cdff",
      midiFillHover: "#2b8c90ff",
      midiBorderHover: "#2b8c90ff",
      midiFillDefault: "#297a7dff",
      midiBorderDefault: "#2b8c90ff",
      midiFillActive: "#26676aff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#2b8c90ff",
    },
  },
  {
    key: "9d",
    name: "Polar Night",
    nexusIndex: 26,
    variables: {
      base: "#1f3050ff",
      regionBody: "#1f3050ff",
      regionBodyAlt: "#1f3050ff",
      regionHeader: "#243f6bff",
      regionHeaderActive: "#243f6bff",
      regionContent: "#5490eeff",
      loopRangeHover: "#2b6fc3ff",
      loopRangeDefault: "#2a5ea5ff",
      loopRangeActive: "#274e87ff",
      loopEdgeHover: "#b4c6f7ff",
      loopEdgeDefault: "#98b3f4ff",
      loopEdgeActive: "#7aa2f1ff",
      midiFillHover: "#2b6fc3ff",
      midiBorderHover: "#2b6fc3ff",
      midiFillDefault: "#2a5ea5ff",
      midiBorderDefault: "#2b6fc3ff",
      midiFillActive: "#274e87ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#243f6bff",
    },
  },
  {
    key: "10d",
    name: "Plum",
    nexusIndex: 27,
    variables: {
      base: "#3b4ae2ff",
      regionBody: "#3b4ae2ff",
      regionBodyAlt: "#3b4ae2ff",
      regionHeader: "#5559f6ff",
      regionHeaderActive: "#5559f6ff",
      regionContent: "#cbbefeff",
      loopRangeHover: "#5559f6ff",
      loopRangeDefault: "#3b4ae2ff",
      loopRangeActive: "#373eb8ff",
      loopEdgeHover: "#cbbefeff",
      loopEdgeDefault: "#b8a9fdff",
      loopEdgeActive: "#a495fbff",
      midiFillHover: "#5559f6ff",
      midiBorderHover: "#5559f6ff",
      midiFillDefault: "#3b4ae2ff",
      midiBorderDefault: "#5559f6ff",
      midiFillActive: "#373eb8ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#5559f6ff",
    },
  },
  {
    key: "11d",
    name: "Purple Haze",
    nexusIndex: 28,
    variables: {
      base: "#542883ff",
      regionBody: "#542883ff",
      regionBodyAlt: "#542883ff",
      regionHeader: "#682fa6ff",
      regionHeaderActive: "#682fa6ff",
      regionContent: "#d1a0fcff",
      loopRangeHover: "#923cf2ff",
      loopRangeDefault: "#7d36cbff",
      loopRangeActive: "#682fa6ff",
      loopEdgeHover: "#ddb8fdff",
      loopEdgeDefault: "#d1a0fcff",
      loopEdgeActive: "#c388fbff",
      midiFillHover: "#923cf2ff",
      midiBorderHover: "#923cf2ff",
      midiFillDefault: "#7d36cbff",
      midiBorderDefault: "#923cf2ff",
      midiFillActive: "#682fa6ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#682fa6ff",
    },
  },
  {
    key: "12d",
    name: "Lipstick",
    nexusIndex: 29,
    variables: {
      base: "#ae36c8ff",
      regionBody: "#ae36c8ff",
      regionBodyAlt: "#ae36c8ff",
      regionHeader: "#c93be8ff",
      regionHeaderActive: "#c93be8ff",
      regionContent: "#eb94faff",
      loopRangeHover: "#da55f6ff",
      loopRangeDefault: "#c93be8ff",
      loopRangeActive: "#ae36c8ff",
      loopEdgeHover: "#f7cbfdff",
      loopEdgeDefault: "#f1b0fcff",
      loopEdgeActive: "#eb94faff",
      midiFillHover: "#da55f6ff",
      midiBorderHover: "#da55f6ff",
      midiFillDefault: "#c93be8ff",
      midiBorderDefault: "#da55f6ff",
      midiFillActive: "#ae36c8ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#c93be8ff",
    },
  },
  {
    key: "1d",
    name: "Crimson",
    nexusIndex: 30,
    variables: {
      base: "#781e16ff",
      regionBody: "#781e16ff",
      regionBodyAlt: "#781e16ff",
      regionHeader: "#962119ff",
      regionHeaderActive: "#962119ff",
      regionContent: "#ff9984ff",
      loopRangeHover: "#b7221cff",
      loopRangeDefault: "#962119ff",
      loopRangeActive: "#781e16ff",
      loopEdgeHover: "#ffb4a3ff",
      loopEdgeDefault: "#ff9984ff",
      loopEdgeActive: "#ff7b64ff",
      midiFillHover: "#b7221cff",
      midiBorderHover: "#b7221cff",
      midiFillDefault: "#962119ff",
      midiBorderDefault: "#b7221cff",
      midiFillActive: "#781e16ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#962119ff",
    },
  },
  {
    key: "2d",
    name: "Zeitgeist",
    nexusIndex: 31,
    variables: {
      base: "#9b612dff",
      regionBody: "#9b612dff",
      regionBodyAlt: "#9b612dff",
      regionHeader: "#b37032ff",
      regionHeaderActive: "#b37032ff",
      regionContent: "#ff9d42ff",
      loopRangeHover: "#b37032ff",
      loopRangeDefault: "#9b612dff",
      loopRangeActive: "#845328ff",
      loopEdgeHover: "#ffd1a6ff",
      loopEdgeDefault: "#ffb877ff",
      loopEdgeActive: "#ff9d42ff",
      midiFillHover: "#b37032ff",
      midiBorderHover: "#b37032ff",
      midiFillDefault: "#9b612dff",
      midiBorderDefault: "#b37032ff",
      midiFillActive: "#845328ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#b37032ff",
    },
  },
  {
    key: "3d",
    name: "Moussaka",
    nexusIndex: 32,
    variables: {
      base: "#3e2d1fff",
      regionBody: "#3e2d1fff",
      regionBodyAlt: "#3e2d1fff",
      regionHeader: "#523a27ff",
      regionHeaderActive: "#523a27ff",
      regionContent: "#d1ad93ff",
      loopRangeHover: "#67482fff",
      loopRangeDefault: "#523a27ff",
      loopRangeActive: "#3e2d1fff",
      loopEdgeHover: "#d1ad93ff",
      loopEdgeDefault: "#c49a7aff",
      loopEdgeActive: "#a97449ff",
      midiFillHover: "#67482fff",
      midiBorderHover: "#67482fff",
      midiFillDefault: "#523a27ff",
      midiBorderDefault: "#67482fff",
      midiFillActive: "#3e2d1fff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#523a27ff",
    },
  },
  {
    key: "4d",
    name: "Circuit",
    nexusIndex: 33,
    variables: {
      base: "#7f6d32ff",
      regionBody: "#7f6d32ff",
      regionBodyAlt: "#7f6d32ff",
      regionHeader: "#927e38ff",
      regionHeaderActive: "#927e38ff",
      regionContent: "#e4c451ff",
      loopRangeHover: "#927e38ff",
      loopRangeDefault: "#7f6d32ff",
      loopRangeActive: "#6c5d2cff",
      loopEdgeHover: "#f9d75fff",
      loopEdgeDefault: "#e4c451ff",
      loopEdgeActive: "#cfb24bff",
      midiFillHover: "#927e38ff",
      midiBorderHover: "#927e38ff",
      midiFillDefault: "#7f6d32ff",
      midiBorderDefault: "#927e38ff",
      midiFillActive: "#6c5d2cff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#927e38ff",
    },
  },
  {
    key: "5d",
    name: "Vacuum",
    nexusIndex: 34,
    variables: {
      base: "#434115ff",
      regionBody: "#434115ff",
      regionBodyAlt: "#434115ff",
      regionHeader: "#535017ff",
      regionHeaderActive: "#535017ff",
      regionContent: "#beb915ff",
      loopRangeHover: "#757219ff",
      loopRangeDefault: "#646118ff",
      loopRangeActive: "#535017ff",
      loopEdgeHover: "#e4df08ff",
      loopEdgeDefault: "#d1cc10ff",
      loopEdgeActive: "#beb915ff",
      midiFillHover: "#757219ff",
      midiBorderHover: "#757219ff",
      midiFillDefault: "#646118ff",
      midiBorderDefault: "#757219ff",
      midiFillActive: "#535017ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#535017ff",
    },
  },
  {
    key: "6d",
    name: "Racing Green",
    nexusIndex: 35,
    variables: {
      base: "#497b22ff",
      regionBody: "#497b22ff",
      regionBodyAlt: "#497b22ff",
      regionHeader: "#528e25ff",
      regionHeaderActive: "#528e25ff",
      regionContent: "#83dd3fff",
      loopRangeHover: "#528e25ff",
      loopRangeDefault: "#497b22ff",
      loopRangeActive: "#3f691fff",
      loopEdgeHover: "#b2e984ff",
      loopEdgeDefault: "#83dd3fff",
      loopEdgeActive: "#70ca2bff",
      midiFillHover: "#528e25ff",
      midiBorderHover: "#528e25ff",
      midiFillDefault: "#497b22ff",
      midiBorderDefault: "#528e25ff",
      midiFillActive: "#3f691fff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#528e25ff",
    },
  },
  {
    key: "13",
    name: "Chocolate",
    nexusIndex: 36,
    variables: {
      base: "#d81657ff",
      regionBody: "#d81657ff",
      regionBodyAlt: "#d81657ff",
      regionHeader: "#ed3366ff",
      regionHeaderActive: "#ed3366ff",
      regionContent: "#591927ff",
      loopRangeHover: "#ed3366ff",
      loopRangeDefault: "#d81657ff",
      loopRangeActive: "#b61b4aff",
      loopEdgeHover: "#771c32ff",
      loopEdgeDefault: "#591927ff",
      loopEdgeActive: "#3d151cff",
      midiFillHover: "#ed3366ff",
      midiBorderHover: "#ed3366ff",
      midiFillDefault: "#d81657ff",
      midiBorderDefault: "#ed3366ff",
      midiFillActive: "#b61b4aff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#ed3366ff",
    },
  },
  {
    key: "13s",
    name: "Rosy Brown",
    nexusIndex: 37,
    variables: {
      base: "#ac516eff",
      regionBody: "#ac516eff",
      regionBodyAlt: "#ac516eff",
      regionHeader: "#b8677fff",
      regionHeaderActive: "#b8677fff",
      regionContent: "#4b2530ff",
      loopRangeHover: "#b8677fff",
      loopRangeDefault: "#ac516eff",
      loopRangeActive: "#97415eff",
      loopEdgeHover: "#632e3fff",
      loopEdgeDefault: "#4b2530ff",
      loopEdgeActive: "#331b22ff",
      midiFillHover: "#b8677fff",
      midiBorderHover: "#b8677fff",
      midiFillDefault: "#ac516eff",
      midiBorderDefault: "#b8677fff",
      midiFillActive: "#97415eff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#b8677fff",
    },
  },
  {
    key: "13d",
    name: "Bistre",
    nexusIndex: 38,
    variables: {
      base: "#771c32ff",
      regionBody: "#771c32ff",
      regionBodyAlt: "#771c32ff",
      regionHeader: "#961d3eff",
      regionHeaderActive: "#961d3eff",
      regionContent: "#fe96a4ff",
      loopRangeHover: "#d81657ff",
      loopRangeDefault: "#b61b4aff",
      loopRangeActive: "#961d3eff",
      loopEdgeHover: "#ffb2bbff",
      loopEdgeDefault: "#fe96a4ff",
      loopEdgeActive: "#fa7a8fff",
      midiFillHover: "#d81657ff",
      midiBorderHover: "#d81657ff",
      midiFillDefault: "#b61b4aff",
      midiBorderDefault: "#d81657ff",
      midiFillActive: "#961d3eff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#961d3eff",
    },
  },
  {
    key: "14",
    name: "Ghost",
    nexusIndex: 39,
    variables: {
      base: "#c6c5d3ff",
      regionBody: "#c6c5d3ff",
      regionBodyAlt: "#c6c5d3ff",
      regionHeader: "#d9d8e2ff",
      regionHeaderActive: "#d9d8e2ff",
      regionContent: "#303037ff",
      loopRangeHover: "#ecebf0ff",
      loopRangeDefault: "#d9d8e2ff",
      loopRangeActive: "#c6c5d3ff",
      loopEdgeHover: "#7e7d94ff",
      loopEdgeDefault: "#6d6d80ff",
      loopEdgeActive: "#5d5d6dff",
      midiFillHover: "#ecebf0ff",
      midiBorderHover: "#ecebf0ff",
      midiFillDefault: "#d9d8e2ff",
      midiBorderDefault: "#ecebf0ff",
      midiFillActive: "#c6c5d3ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#d9d8e2ff",
    },
  },
  {
    key: "14s",
    name: "Bright Gray",
    nexusIndex: 40,
    variables: {
      base: "#7e7d94ff",
      regionBody: "#7e7d94ff",
      regionBodyAlt: "#7e7d94ff",
      regionHeader: "#8e8ea8ff",
      regionHeaderActive: "#8e8ea8ff",
      regionContent: "#303037ff",
      loopRangeHover: "#8e8ea8ff",
      loopRangeDefault: "#7e7d94ff",
      loopRangeActive: "#6d6d80ff",
      loopEdgeHover: "#4d4d5aff",
      loopEdgeDefault: "#3e3e48ff",
      loopEdgeActive: "#303037ff",
      midiFillHover: "#8e8ea8ff",
      midiBorderHover: "#8e8ea8ff",
      midiFillDefault: "#7e7d94ff",
      midiBorderDefault: "#8e8ea8ff",
      midiFillActive: "#6d6d80ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#8e8ea8ff",
    },
  },
  {
    key: "14d",
    name: "Dark Gray",
    nexusIndex: 41,
    variables: {
      base: "#222226ff",
      regionBody: "#222226ff",
      regionBodyAlt: "#222226ff",
      regionHeader: "#303037ff",
      regionHeaderActive: "#303037ff",
      regionContent: "#8e8ea8ff",
      loopRangeHover: "#3e3e48ff",
      loopRangeDefault: "#303037ff",
      loopRangeActive: "#222226ff",
      loopEdgeHover: "#a1a0b7ff",
      loopEdgeDefault: "#8e8ea8ff",
      loopEdgeActive: "#7e7d94ff",
      midiFillHover: "#3e3e48ff",
      midiBorderHover: "#3e3e48ff",
      midiFillDefault: "#303037ff",
      midiBorderDefault: "#3e3e48ff",
      midiFillActive: "#222226ff",
      midiBorderActive: "#eaecefff",
      mixerStrip: "#303037ff",
    },
  },
];
